include: '../config.py'

rule all:
    input:
        KALLISTO,
        RSEM_SIMULATE

rule get_kallisto:
    output:
        KALLISTO
    params:
        url = 'https://github.com/pachterlab/kallisto/releases/download/v0.42.4/kallisto_linux-v0.42.4.tar.gz'
    shell:
        'wget -O kallisto_binary.tar.gz {params.url}; '
        'tar -xf kallisto_binary.tar.gz; '
        'rmdir kallisto_linux; ' # snakemake will automatically make this directory
        'mv kallisto_linux-* kallisto_linux; '

rule get_rsem_simulate:
    output:
        RSEM_SIMULATE
    params:
        url = 'https://github.com/pimentel/RSEM',
        tmp = 'rsem_simulate_tmp'
    shell:
        'git clone --branch simulate-counts --depth 1 {params.url} {params.tmp};'
        ' cd {params.tmp};'
        ' make;'
        # 'make rsem-simulate-reads; '
        ' cd ..;'
        ' rmdir rsem_simulate;'
        ' mv {params.tmp} rsem_simulate;'
